part of 'resources.dart';

class Ics {
  Ics._();

  static const String icAlert = 'assets/icons/ic_alert.svg';
  static const String icAlign = 'assets/icons/ic_align.svg';
  static const String icArrowDown = 'assets/icons/ic_arrow_down.svg';
  static const String icArrowLeft = 'assets/icons/ic_arrow_left.svg';
  static const String icArrowLeft2 = 'assets/icons/ic_arrow_left_2.svg';
  static const String icArrowRight = 'assets/icons/ic_arrow_right.svg';
  static const String icArrowRight2 = 'assets/icons/ic_arrow_right_2.svg';
  static const String icArrowUp = 'assets/icons/ic_arrow_up.svg';
  static const String icBoomer = 'assets/icons/ic_boomer.svg';
  static const String icCalendar = 'assets/icons/ic_calendar.svg';
  static const String icCall = 'assets/icons/ic_call.svg';
  static const String icCallHurry = 'assets/icons/ic_call_hurry.svg';
  static const String icCertain = 'assets/icons/ic_certain.svg';
  static const String icCheck = 'assets/icons/ic_check.svg';
  static const String icCheckBox = 'assets/icons/ic_check_box.svg';
  static const String icCheckCircle = 'assets/icons/ic_check_circle.svg';
  static const String icCircle = 'assets/icons/ic_circle.svg';
  static const String icCircleCheck = 'assets/icons/ic_circle_check.svg';
  static const String icClipboardOutline =
      'assets/icons/ic_clipboard_outline.svg';
  static const String icClipboardSolid = 'assets/icons/ic_clipboard_solid.svg';
  static const String icClose = 'assets/icons/ic_close.svg';
  static const String icContact = 'assets/icons/ic_contact.svg';
  static const String icContact2 = 'assets/icons/ic_contact_2.svg';
  static const String icCrownFill = 'assets/icons/ic_crown_fill.svg';
  static const String icCrownLine = 'assets/icons/ic_crown_line.svg';
  static const String icDelete = 'assets/icons/ic_delete.svg';
  static const String icDog = 'assets/icons/ic_dog.svg';
  static const String icDownload = 'assets/icons/ic_download.svg';
  static const String icEdit = 'assets/icons/ic_edit.svg';
  static const String icEmailBox = 'assets/icons/ic_email_box.svg';
  static const String icEmptyBox = 'assets/icons/ic_empty_box.svg';
  static const String icFiery = 'assets/icons/ic_fiery.svg';
  static const String icFilter = 'assets/icons/ic_filter.svg';
  static const String icFinger = 'assets/icons/ic_finger.svg';
  static const String icFresh = 'assets/icons/ic_fresh.svg';
  static const String icFriendly = 'assets/icons/ic_friendly.svg';
  static const String icGlyphs = 'assets/icons/ic_glyphs.svg';
  static const String icGroupPlus = 'assets/icons/ic_group_plus.svg';
  static const String icHeadstrong = 'assets/icons/ic_headstrong.svg';
  static const String icHomeFill = 'assets/icons/ic_home_fill.svg';
  static const String icHomeLine = 'assets/icons/ic_home_line.svg';
  static const String icIdiot = 'assets/icons/ic_idiot.svg';
  static const String icKakaotalk = 'assets/icons/ic_kakaotalk.svg';
  static const String icLate = 'assets/icons/ic_late.svg';
  static const String icList = 'assets/icons/ic_list.svg';
  static const String icLoading = 'assets/icons/ic_loading.svg';
  static const String icLogout = 'assets/icons/ic_logout.svg';
  static const String icMail = 'assets/icons/ic_mail.svg';
  static const String icMessage = 'assets/icons/ic_message.svg';
  static const String icNote = 'assets/icons/ic_note.svg';
  static const String icNotie = 'assets/icons/ic_notie.svg';
  static const String icNotieFill = 'assets/icons/ic_notie_fill.svg';
  static const String icOverbearing = 'assets/icons/ic_overbearing.svg';
  static const String icPassword = 'assets/icons/ic_password.svg';
  static const String icPhotoLibrary = 'assets/icons/ic_photo_library.svg';
  static const String icPlus = 'assets/icons/ic_plus.svg';
  static const String icRadioOn = 'assets/icons/ic_radio_on.svg';
  static const String icRefresh = 'assets/icons/ic_refresh.svg';
  static const String icRefresh2 = 'assets/icons/ic_refresh_2.svg';
  static const String icRefreshIng = 'assets/icons/ic_refresh_ing.svg';
  static const String icReportFill = 'assets/icons/ic_report_fill.svg';
  static const String icReportLine = 'assets/icons/ic_report_line.svg';
  static const String icSFilter = 'assets/icons/ic_s_filter.svg';
  static const String icSearch = 'assets/icons/ic_search.svg';
  static const String icSetting = 'assets/icons/ic_setting.svg';
  static const String icShare = 'assets/icons/ic_share.svg';
  static const String icSmile = 'assets/icons/ic_smile.svg';
  static const String icSnaky = 'assets/icons/ic_snaky.svg';
  static const String icTagFill = 'assets/icons/ic_tag_fill.svg';
  static const String icTagLine = 'assets/icons/ic_tag_line.svg';
  static const String icTagPlus = 'assets/icons/ic_tag_plus.svg';
  static const String icTimid = 'assets/icons/ic_timid.svg';
  static const String icTripleArrowRight =
      'assets/icons/ic_triple_arrow_right.svg';
  static const String icTrustworthy = 'assets/icons/ic_trustworthy.svg';
  static const String icUnspecified = 'assets/icons/ic_unspecified.svg';
  static const String icUsers = 'assets/icons/ic_users.svg';
  static const String icWhatever = 'assets/icons/ic_whatever.svg';
}
